# Generated by Django 5.0.6 on 2024-06-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_object_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('brief_description', models.TextField()),
                ('donated_loan_by', models.CharField(max_length=255)),
                ('copyright', models.CharField(max_length=255)),
                ('associated_people', models.TextField()),
                ('associated_places', models.TextField()),
                ('home_location', models.CharField(max_length=255)),
                ('date_received', models.DateField()),
                ('current_location', models.CharField(max_length=255)),
                ('physical_description', models.TextField()),
                ('size', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('id_number', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
