# Generated by Django 5.0.6 on 2024-06-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=255),
        ),
    ]
